import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.3)
mengetik('\n    Akses Diminta')
time.sleep(random.random() * 0.5)
mengetik('      50%')
mengetik('      100%')
time.sleep(random.random() * 0.2)
mengetik('      Menghubungi KINGBOYING. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      50%')
mengetik('      100%')
time.sleep(random.random() * 0.2)
mengetik('      Mencoba Meminta Akses Ke KINGBOYING. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      AKSES DITERIMA')
mengetik('      SELAMAT, KAMU BERHASIL LOGIN')
time.sleep(random.random() * 0.2)
mengetik('      Silahkan gunakan script ini. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      Gunakan Sebijak Mungkin')
mengetik('      Dilarang Menyebarkan script')
mengetik('      Tanpa Seizin - Bang Ariel ;)')
mengetik('      Script VIP')
time.sleep(random.random() * 0.2)
mengetik('      Cek Status !. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      Script Siap Di Gunakan')
mengetik('      Semua Fitur Bisa Di Akses.')
time.sleep(random.random() * 0.3)
mengetik('      licensi : ydu+i674h6764778_3ijr9nee+990)')
mengetik('      Selamat mencoba')
