import random
import sys
import time
def mengetik(s):
    for c in s + '\n':
        sys.stdout.write(c)
        sys.stdout.flush()
        time.sleep(random.random() * 0.3)
mengetik('\n    Sukses Login!')
time.sleep(random.random() * 0.5)
mengetik('      50%')
mengetik('      100%')
time.sleep(random.random() * 0.2)
mengetik('      Menghubungi AAY_ID. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      50%')
mengetik('      100%')
time.sleep(random.random() * 0.2)
mengetik('      Mencoba Meminta Akses. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      50%')
mengetik('      100%')
time.sleep(random.random() * 0.2)
mengetik('      Upgrade!. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      25%')
mengetik('      50%')
mengetik('      80%')
mengetik('      100%')
time.sleep(random.random() * 0.2)
mengetik('      Update!. . . . .')
time.sleep(random.random() * 0.5)
mengetik('      50%')
mengetik('      100%')
time.sleep(random.random() * 0.3)
mengetik('      ydu+i674h6764778_3ijr9nee+990)')
mengetik('      Sukses!')